// ─── User ───────────────────────────────────────────────────────────────────
export interface User {
  id: string;
  email: string;
  firebase_uid?: string;
  full_name?: string;
  username?: string;
  github_login?: string;
  avatar_url?: string;
  github_avatar?: string;
  is_active: boolean;
  created_at: string;
}

// ─── GitHub repository discovery ────────────────────────────────────────────
export interface GitHubRepo {
  id: string;
  name: string;
  full_name: string;
  html_url: string;
  default_branch: string;
  private: boolean;
  updated_at: string;
  language?: string;
  description?: string;
}

export interface Branch {
  name: string;
  protected: boolean;
}

// ─── Project ────────────────────────────────────────────────────────────────
// Repository metadata is stored directly on the project because one project
// has exactly one connected repository.
export interface ProjectRepository {
  github_repo_id?: string;
  owner?: string;
  name?: string;
  full_name?: string;
  html_url?: string;
  default_branch?: string;
  language?: string;
  description?: string;
  private: boolean;
  visibility?: string;
  size_kb: number;
  frameworks?: string;
  package_manager?: string;
}

export interface Project {
  id: string;
  user_id: string;
  name?: string;
  description?: string;
  branch: string;
  deployment_url?: string;
  verified: boolean;
  created_at: string;

  repo_id?: string;
  repo_owner?: string;
  repo_name?: string;
  repo_url?: string;
  default_branch?: string;
  repo_language?: string;
  repo_description?: string;
  repo_private: boolean;
  repo_visibility?: string;
  repo_size_kb: number;
  repo_frameworks?: string;
  repo_package_manager?: string;

  // Compatibility view generated by the API; this is not a DB relationship.
  repository?: ProjectRepository;
  targets?: TargetWebsite[];
  scans?: Scan[];
}

export type ScanStatus =
  | 'QUEUED'
  | 'INGESTING'
  | 'SCANNING'
  | 'NORMALIZING'
  | 'COMPLETED'
  | 'PARTIAL'
  | 'FAILED'
  | 'CANCELLED';

export interface ScanEngineRun {
  id: string;
  scan_id: string;
  engine_name: string;
  container_name?: string;
  status: string;
  exit_code?: number;
  duration_ms?: number;
  artifact_reference?: string;
  error_message?: string;
  started_at?: string;
  completed_at?: string;
  created_at: string;
}

export interface Scan {
  id: string;
  project_id: string;
  analysis_run_id: string;
  commit_sha: string;
  status: ScanStatus | string;
  progress_percent: number;
  current_stage?: string;
  error_message?: string;
  created_at: string;
  started_at?: string;
  completed_at?: string;
}

export interface ScanStatusResponse extends Scan {
  engine_statuses: Record<string, string>;
  engine_runs: ScanEngineRun[];
}

// ─── Target Website ─────────────────────────────────────────────────────────
export interface TargetWebsite {
  id: string;
  project_id: string;
  domain: string;
  verification_token: string;
  is_verified: boolean;
  verified_at?: string;
  created_at: string;
}

export interface VerificationResult {
  target_id: string;
  domain: string;
  is_verified: boolean;
  message: string;
  checked_url: string;
  verified_at?: string;
}

// ─── Project API payloads ────────────────────────────────────────────────────
export interface RepositoryReference {
  github_repo_id: string;
  owner: string;
  name: string;
  full_name: string;
  html_url?: string;
  default_branch?: string;
  language?: string;
  description?: string;
  private?: boolean;
}

export interface CreateProjectPayload {
  name?: string;
  description?: string;
  repository: RepositoryReference;
  branch?: string;
  deployment_url?: string;
}

export interface UpdateProjectPayload {
  name?: string;
  description?: string;
  branch?: string;
  deployment_url?: string;
  verified?: boolean;
}

// ─── Phase 2 ingestion ──────────────────────────────────────────────────────
export interface AnalysisRun {
  id: string;
  project_id: string;
  commit_sha?: string;
  status: string;
  files_found: number;
  files_ingested: number;
  files_skipped: number;
  languages_summary?: string;
  frameworks?: string;
  package_manager?: string;
  error_message?: string;
  started_at: string;
  completed_at?: string;
}

export interface AnalysisSummary {
  project_id: string;
  commit_sha?: string;
  files_found: number;
  files_ingested: number;
  files_skipped: number;
  languages: Record<string, number>;
  frameworks?: string;
  package_manager?: string;
  status: string;
  run_id: string;
}

export interface RepositoryFile {
  id: string;
  project_id: string;
  analysis_run_id: string;
  path: string;
  filename: string;
  extension?: string;
  language?: string;
  size: number;
  sha256?: string;
  content?: string;
  status: string;
  skip_reason?: string;
  created_at: string;
}
